# See dynamic_inventory.py for the variables used in this file.
---
-   hosts: nd
    check_mode: false
    gather_facts: false
    vars:
    tasks:
    - name: "{{ SITE1_FABRIC }}.L1 switch_freeform policy IP4_L1_H1"
      cisco.dcnm.dcnm_policy:
        state: merged
        fabric: "{{ SITE1_FABRIC }}"
        use_desc_as_key: true
        config:
          - switch:
            - ip: "{{ L1_IP4 }}"
              policies:
                - name: switch_freeform
                  create_additional_policy: false
                  priority: 101
                  description: L1_interface_IP4_L1_H1
                  policy_vars:
                    CONF: |
                      configure terminal
                        interface {{ L1_INTERFACE_2 }}
                          no switchport
                          ip address {{ L1_IP4_INTERFACE_2 }}/{{ L1_IP4_MASK }}
