# See dynamic_inventory.py for the variables used in this file.
---
-   hosts: nd
    check_mode: false
    gather_facts: false
    vars:
    tasks:
    - name: "{{ ISN_FABRIC }}.ER switch_freeform policy"
      cisco.dcnm.dcnm_policy:
        state: merged
        fabric: "{{ ISN_FABRIC }}"
        use_desc_as_key: true
        config:
          - switch:
            - ip: "{{ ER_IP4 }}"
              policies:
                - name: switch_freeform
                  create_additional_policy: false
                  priority: 101
                  description: ER_interface_mac_addresses
                  policy_vars:
                    CONF: |
                      configure terminal
                        interface {{ ER_INTERFACE_1 }}
                          no switchport
                          mac-address {{ ER_MAC_1 }}
                        interface {{ ER_INTERFACE_2 }}
                          no switchport
                          mac-address {{ ER_MAC_2 }}

