---
-   hosts: nd
    check_mode: false
    gather_facts: false
    vars:
    tasks:
    - name: Create ISN.ER switch policies
      cisco.dcnm.dcnm_policy:
        state: merged
        fabric: "{{ FABRIC_ISN }}"
        use_desc_as_key: true
        config:
          - switch:
            - ip: "{{ ER_IP4 }}"
              policies:
                - name: switch_freeform
                  create_additional_policy: false
                  priority: 101
                  description: ER_interface_mac_addresses
                  policy_vars:
                    CONF: |
                      configure terminal
                        interface {{ ER_INTERFACE_1 }}
                          mac-address {{ ER_MAC_1 }}
                        interface {{ ER_INTERFACE_2 }}
                          mac-address {{ ER_MAC_2 }}

