---
-   hosts: nd
    check_mode: false
    gather_facts: false
    vars:
    tasks:
    - name: Create f1.S2 switch policies
      cisco.dcnm.dcnm_policy:
        state: merged
        fabric: "{{ FABRIC_VXLAN }}"
        use_desc_as_key: true
        config:
          - switch:
            - ip: "{{ S2_IP4 }}"
              policies:
                - name: switch_freeform
                  create_additional_policy: false
                  priority: 101
                  description: S2_interface_mac_addresses
                  policy_vars:
                    CONF: |
                      configure terminal
                        interface {{ S2_INTERFACE_1 }}
                          mac-address {{ S2_MAC_1 }}
                        interface {{ S2_INTERFACE_2 }}
                          mac-address {{ S2_MAC_2 }}
