---
-   hosts: nd
    check_mode: false
    gather_facts: false
    tasks:
    - name: Networks SITE2
      cisco.dcnm.dcnm_network:
        fabric: SITE2
        state: merged
        config:
        - net_name: v2n1
          vrf_name: v2
          net_id: 2
          net_template: Default_Network_Universal
          net_extension_template: Default_Network_Extension_Universal
          vlan_id: 2
          gw_ip_subnet: 192.0.1.1/24
          deploy: true
          attach:
          - ip_address: "{{ SP2_IP4 }}"
          - ip_address: "{{ LE2_IP4 }}"
        - net_name: v3n1
          vrf_name: v3
          net_id: 3
          net_template: Default_Network_Universal
          net_extension_template: Default_Network_Extension_Universal
          vlan_id: 3
          gw_ip_subnet: 192.0.2.1/24
          deploy: true
          attach:
          - ip_address: "{{ SP2_IP4 }}"
          - ip_address: "{{ LE2_IP4 }}"
