---
-   hosts: nd
    check_mode: false
    gather_facts: false
    tasks:
    - name: Networks SITE1
      cisco.dcnm.dcnm_network:
        fabric: SITE1
        state: merged
        config:
        - net_name: NET2
          vrf_name: VRF2
          net_id: 2
          net_template: Default_Network_Universal
          net_extension_template: Default_Network_Extension_Universal
          vlan_id: 2
          gw_ip_subnet: 22.1.1.1/24
          deploy: true
          attach:
          - ip_address: 192.168.12.121
            ports: []
          - ip_address: 192.168.12.131
            ports:
            - Ethernet1/2
