---
-   hosts: nd
    check_mode: false
    gather_facts: false
    tasks:
    - name: Networks MSD
      cisco.dcnm.dcnm_network:
        fabric: MSD
        state: merged
        config:
        - net_name: n2
          vrf_name: v2
          net_id: 2
          net_template: Default_Network_Universal
          net_extension_template: Default_Network_Extension_Universal
          vlan_id: 2
          gw_ip_subnet: 11.1.2.1/24
          deploy: true
          attach:
          - ip_address: "{{ L1_IP4 }}"
          - ip_address: "{{ L2_IP4 }}"
          - ip_address: "{{ S1_IP4 }}"
          - ip_address: "{{ S2_IP4 }}"
        - net_name: n3
          vrf_name: v3
          net_id: 3
          net_template: Default_Network_Universal
          net_extension_template: Default_Network_Extension_Universal
          vlan_id: 3
          gw_ip_subnet: 11.1.3.1/24
          deploy: true
          attach:
          - ip_address: "{{ L1_IP4 }}"
          - ip_address: "{{ L2_IP4 }}"
          - ip_address: "{{ S1_IP4 }}"
          - ip_address: "{{ S2_IP4 }}"
