---
-   hosts: ndfc
    check_mode: false
    gather_facts: false
    vars:
        fabric_name: ISN
        switch_ip: 192.168.11.111
        mac_address_1: 0000.0011.0001
        mac_address_2: 0000.0011.0002
        deploy: true
        admin_state: true
        type: eth
    tasks:
    - name: ER interface mac-address configuration
    cisco.dcnm.dcnm_interface:
        fabric: "{{ fabric_name }}"
        state: merged
        config:
        - name: Ethernet1/1
            type: Ethernet1/1
            switch:
              - "{{ switch_ip }}"
            deploy: true
            profile:
              admin_state: "{{ admin_state }}"
              cmds:
                - mac-address {{ mac_address_1 }}
        - name: Ethernet1/2
            type: eth
            switch:
              - "{{ switch_ip }}"
            deploy: true
            profile:
              admin_state: "{{ admin_state }}"
              cmds:
                - mac-address {{ mac_address_2 }}
