---
-   hosts: nd
    check_mode: false
    gather_facts: false
    vars:
        FABRIC_ISN: ISN
        FABRIC_VXLAN: f1
        ER_IP: 192.168.11.111
        ER_MAC_1: 0000.0011.0001
        ER_MAC_2: 0000.0011.0002
        S1_IP: 192.168.11.121
        S1_MAC_1: 0000.0021.0001
        S1_MAC_2: 0000.0021.0002
        S2_IP: 192.168.11.122
        S2_MAC_1: 0000.0022.0001
        S2_MAC_2: 0000.0022.0002
        L1_IP: 192.168.11.131
        L1_MAC_1: 0000.0031.0001
        L1_MAC_2: 0000.0031.0002
        admin_state: true
    tasks:
    - name: Create ISN switch policies
      cisco.dcnm.dcnm_policy:
        state: merged
        fabric: "{{ FABRIC_ISN }}"
        use_desc_as_key: true
        config:
          - switch:
            - ip: "{{ ER_IP }}"
              policies:
                - name: switch_freeform
                  create_additional_policy: false
                  priority: 101
                  description: ER_interface_mac_addresses
                  policy_vars:
                    CONF: |
                      configure terminal
                        interface Ethernet1/1
                          mac-address {{ ER_MAC_1 }}
                        interface Ethernet1/2
                          mac-address {{ ER_MAC_2 }}
    - name: Create f1 switch policies
      cisco.dcnm.dcnm_policy:
        state: merged
        fabric: "{{ FABRIC_VXLAN }}"
        use_desc_as_key: true
        config:
          - switch:
            - ip: "{{ S1_IP }}"
              policies:
                - name: switch_freeform
                  create_additional_policy: false
                  priority: 101
                  description: S1_interface_mac_addresses
                  policy_vars:
                    CONF: |
                      interface Ethernet1/1
                        mac-address {{ S1_MAC_1 }}
                      interface Ethernet1/2
                        mac-address {{ S1_MAC_2 }}
          - switch:
            - ip: "{{ S2_IP }}"
              policies:
                - name: switch_freeform
                  create_additional_policy: false
                  priority: 101
                  description: S2_interface_mac_addresses
                  policy_vars:
                    CONF: |
                      interface Ethernet1/1
                        mac-address {{ S2_MAC_1 }}
                      interface Ethernet1/2
                        mac-address {{ S2_MAC_2 }}
          - switch:
            - ip: "{{ L1_IP }}"
              policies:
                - name: switch_freeform
                  create_additional_policy: false
                  priority: 101
                  description: L1_interface_mac_addresses
                  policy_vars:
                    CONF: |
                      interface Ethernet1/1
                        mac-address {{ L1_MAC_1 }}
                      interface Ethernet1/2
                        mac-address {{ L1_MAC_2 }}
