---
-   hosts: nd
    check_mode: false
    gather_facts: false
    vars:
        fabric_name: ISN
        switch_ip: 192.168.11.122
        mac_address_1: 0000.0022.0001
        mac_address_2: 0000.0022.0002
        admin_state: true
    tasks:
    - name: S2 interface mac-address configuration
      cisco.dcnm.dcnm_interface:
        fabric: "{{ fabric_name }}"
        state: merged
        config:
        - name: Ethernet1/1
          type: eth
          switch:
            - "{{ switch_ip }}"
          deploy: true
          profile:
            admin_state: "{{ admin_state }}"
            mode: routed
            cmds:
              - mac-address {{ mac_address_1 }}
        - name: Ethernet1/2
          type: eth
          switch:
            - "{{ switch_ip }}"
          deploy: true
          profile:
            admin_state: "{{ admin_state }}"
            mode: routed
            cmds:
              - mac-address {{ mac_address_2 }}
