---
-   hosts: nd
    check_mode: false
    gather_facts: false
    vars:
        FABRIC_NAME: ISN
        ER_IP: 192.168.11.111
        ER_MAC_1: 0000.0011.0001
        ER_MAC_2: 0000.0011.0002
    tasks:
    - name: Create ISN.ER switch policies
      cisco.dcnm.dcnm_policy:
        state: merged
        fabric: "{{ FABRIC_NAME }}"
        use_desc_as_key: true
        config:
          - switch:
            - ip: "{{ ER_IP }}"
              policies:
                - name: switch_freeform
                  create_additional_policy: false
                  priority: 101
                  description: ER_interface_mac_addresses
                  policy_vars:
                    CONF: |
                      configure terminal
                        interface Ethernet1/1
                          mac-address {{ ER_MAC_1 }}
                        interface Ethernet1/2
                          mac-address {{ ER_MAC_2 }}

