---
# SITE1
# S1_BG1.yaml - Border Gateway 1 in SITE1
name: S1_BG1
role: Border Gateway
sid: 1301
mgmt_bridge: BR_ND_DATA_12
mgmt_ip: 192.168.12.131/24
mgmt_gw: 192.168.12.1
neighbors:
  - S2_BG1
  - S1_SP1
isl_bridges:
  - BR_ISN_S1_S2_1
  - BR_S1_BG1_SP1_1
