---
# SITE1
# S1_LE4.yaml - Leaf Switch 4 in SITE1 (VPC pair member with S1_LE3)
name: S1_LE4
role: Leaf Switch
sid: 1504
mgmt_bridge: BR_ND_DATA_12
mgmt_ip: 192.168.12.155/24
mgmt_gw: 192.168.12.1
neighbors:
  - S1_SP1
  - S1_LE3
isl_bridges:
  - BR_S1_SP1_LE4_1
  - BR_S1_LE3_LE4_1
