network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      addresses:
        - 192.168.12.161/24
      dhcp4: false
      dhcp6: false
      accept-ra: true
      link-local: [ipv6]
      
    eth1:
      addresses:
        - 192.0.1.161/24
        - 2001:192:0:1:200:41ff:fe00:2/64
      dhcp4: false
      dhcp6: false
      accept-ra: true
      link-local: [ipv6]
      routes:
        - to: 10.19.0.2/32
          via: 192.0.1.1
        - to: 10.29.0.2/32
          via: 192.0.1.1
