---
# SITE3 (ND 4.3.1 mirror of SITE1)
# S3_LE2.yaml - Leaf Switch 2 in SITE3 (VPC pair member with S3_LE1; downstream of S3_TOR1; mirror of S1_LE2)
name: S3_LE2
role: Leaf Switch
sid: 3502
mgmt_bridge: BR_ND_DATA_14
mgmt_ip: 192.168.14.152/24
mgmt_gw: 192.168.14.1
neighbors:
  - S3_SP1
  - S3_LE1
  - S3_TOR1
isl_bridges:
  - BR_S3_SP1_LE2_1
  - BR_S3_LE1_LE2_1
  - BR_S3_LE2_T1_1
