---
# SITE3 (ND 4.3.1 mirror of SITE1)
# S3_LE4.yaml - Leaf Switch 4 in SITE3 (VPC pair member with S3_LE3; mirror of S1_LE4)
name: S3_LE4
role: Leaf Switch
sid: 3504
mgmt_bridge: BR_ND_DATA_14
mgmt_ip: 192.168.14.155/24
mgmt_gw: 192.168.14.1
neighbors:
  - S3_SP1
  - S3_LE3
isl_bridges:
  - BR_S3_SP1_LE4_1
  - BR_S3_LE3_LE4_1
