---
# SITE3
# S3_LE1.yaml - Leaf Switch 1 in SITE3
name: S3_LE1
role: Leaf Switch
sid: 53
mgmt_bridge: BR_ND_DATA_14
neighbors:
  - S3_SP1
  - S3_H1
isl_bridges:
  - BR_S3_SP1_LE1_1
  - BR_S3_LE1_H1_1
