---
# SITE3
# S3_SP1.yaml - Spine Switch 1 in SITE3
name: S3_SP1
role: Spine Switch
sid: 43
mgmt_bridge: BR_ND_DATA_14
neighbors:
  - S3_BG1
  - S3_LE1
isl_bridges:
  - BR_S3_BG1_SP1_1
  - BR_S3_SP1_LE1_1
