---
# SITE4
# S4_LE2.yaml - Leaf Switch 2 in SITE4 (was VP3; VPC pair member with S4_LE3 toward S4_H2)
name: S4_LE2
role: Leaf Switch
sid: 63
mgmt_bridge: BR_ND_DATA_14
neighbors:
  - S4_SP1
  - S4_H2
isl_bridges:
  - BR_S4_SP1_LE2_1
  - BR_S4_LE2_H2_1
