---
# SITE4
# S4_LE3.yaml - Leaf Switch 3 in SITE4 (was VP4; VPC pair member with S4_LE2 toward S4_H2)
name: S4_LE3
role: Leaf Switch
sid: 4503
mgmt_bridge: BR_ND_DATA_14
mgmt_ip: 192.168.14.154/24
mgmt_gw: 192.168.14.1
neighbors:
  - S4_SP1
  - S4_H2
isl_bridges:
  - BR_S4_SP1_LE3_1
  - BR_S4_LE3_H2_1
