---
# SITE4
# S4_SP1.yaml - Spine Switch 1 in SITE4
name: S4_SP1
role: Spine Switch
sid: 4401
mgmt_bridge: BR_ND_DATA_14
mgmt_ip: 192.168.14.142/24
mgmt_gw: 192.168.14.1
neighbors:
  - S4_BG1
  - S4_LE1
  - S4_LE2
  - S4_LE3
isl_bridges:
  - BR_S4_BG1_SP1_1
  - BR_S4_SP1_LE1_1
  - BR_S4_SP1_LE2_1
  - BR_S4_SP1_LE3_1
