---
# SP4.yaml - Spine Switch 4 configuration
name: SP4
role: Spine Switch
sid: 44
mgmt_bridge: BR_ND_DATA_14
neighbors:
  - BG4
  - LE4
  - VP3
  - VP4
isl_bridges:
  - BR_BG4_SP4
  - BR_SP4_LE4
  - BR_SP4_VP3
  - BR_SP4_VP4
