network:
  version: 2
  ethernets:
    eno5:
      dhcp4: false
      dhcp6: false
      optional: true
      accept-ra: false
    eno6:
      dhcp4: false
      dhcp6: false
      optional: true
      accept-ra: false
  bridges:
    outside:
      interfaces:
        - eno5
      addresses:
        - 10.10.20.7/16
      routes:
        - to: 0.0.0.0/0
          via: 10.10.0.1
        - to: "::/0"
          via: fe80::76fa:29ff:fe48:4bed
      optional: false
      accept-ra: true
      parameters:
        stp: false
        forward-delay: 0

