# This provides the bridge configurations used for SITE3/SITE4
# in this repository.  This is needed ONLY if you want a second
# virtual testbed on the same host.  For example, you could
# use a second testbed for a different version of Nexus Dashboard.
#
# Copy it to /etc/netplan/9914-bridges.yaml on the target system.
# sudo cp 9914-bridges.yaml /etc/netplan/9914-bridges.yaml
# sudo chmod 600 /etc/netplan/9914-bridges.yaml
# sudo netplan try
# sudo netplan apply

# Bridge names are outlined below, along with the interfaces they connect.
#
# Src Interface           Dst Interface           Bridge                       Site
# S3_BG1_INTERFACE_1      S4_BG1_INTERFACE_1      BR_ISN_S3_S4_1         MSD inter-site
# S3_BG1_INTERFACE_2      S3_SP1_INTERFACE_1      BR_S3_BG1_SP1_1              SITE3
# S4_BG1_INTERFACE_2      S4_SP1_INTERFACE_1      BR_S4_BG1_SP1_1              SITE4
# S3_SP1_INTERFACE_2      S3_LE1_INTERFACE_1      BR_S3_SP1_LE1_1              SITE3
# S4_SP1_INTERFACE_2      S4_LE1_INTERFACE_1      BR_S4_SP1_LE1_1              SITE4
# S3_LE1_INTERFACE_2      S3_H1_INTERFACE_1       BR_S3_LE1_H1_1               SITE3
# S4_LE1_INTERFACE_2      S4_H1_INTERFACE_1       BR_S4_LE1_H1_1               SITE4
# S4_SP1_INTERFACE_3      S4_LE2_INTERFACE_1      BR_S4_SP1_LE2_1              SITE4
# S4_SP1_INTERFACE_4      S4_LE3_INTERFACE_1      BR_S4_SP1_LE3_1              SITE4
# S4_LE2_INTERFACE_2      S4_H2_INTERFACE_1       BR_S4_LE2_H2_1               SITE4
# S4_LE3_INTERFACE_2      S4_H2_INTERFACE_2       BR_S4_LE3_H2_1               SITE4

network:
  version: 2
  renderer: networkd
  vlans:
    Vlan14:
      id: 14
      link: eno6
      optional: true
  bridges:

    BR_ISN_S3_S4_1:
      openvswitch: {}
      dhcp4: false
      dhcp6: false
      mtu: 9216
      accept-ra: false
      parameters:
        stp: false
      interfaces: []

    BR_S3_BG1_SP1_1:
      openvswitch: {}
      dhcp4: false
      dhcp6: false
      mtu: 9216
      accept-ra: false
      parameters:
        stp: false
      interfaces: []

    BR_S4_BG1_SP1_1:
      openvswitch: {}
      dhcp4: false
      dhcp6: false
      mtu: 9216
      accept-ra: false
      parameters:
        stp: false
      interfaces: []

    BR_S3_SP1_LE1_1:
      openvswitch: {}
      dhcp4: false
      dhcp6: false
      mtu: 9216
      accept-ra: false
      parameters:
        stp: false
      interfaces: []

    BR_S4_SP1_LE1_1:
      openvswitch: {}
      dhcp4: false
      dhcp6: false
      mtu: 9216
      accept-ra: false
      parameters:
        stp: false
      interfaces: []

    BR_S4_SP1_LE2_1:
      openvswitch: {}
      dhcp4: false
      dhcp6: false
      mtu: 9216
      accept-ra: false
      parameters:
        stp: false
      interfaces: []

    BR_S4_SP1_LE3_1:
      openvswitch: {}
      dhcp4: false
      dhcp6: false
      mtu: 9216
      accept-ra: false
      parameters:
        stp: false
      interfaces: []

    BR_S3_LE1_H1_1:
      openvswitch: {}
      dhcp4: false
      dhcp6: false
      mtu: 9216
      accept-ra: false
      parameters:
        stp: false
      interfaces: []

    BR_S4_LE1_H1_1:
      openvswitch: {}
      dhcp4: false
      dhcp6: false
      mtu: 9216
      accept-ra: false
      parameters:
        stp: false
      interfaces: []

    BR_S4_LE2_H2_1:
      openvswitch: {}
      dhcp4: false
      dhcp6: false
      mtu: 9216
      accept-ra: false
      parameters:
        stp: false
      interfaces: []

    BR_S4_LE3_H2_1:
      openvswitch: {}
      dhcp4: false
      dhcp6: false
      mtu: 9216
      accept-ra: false
      parameters:
        stp: false
      interfaces: []

    BR_ND_DATA_14:
      openvswitch: {}
      interfaces:
      - Vlan14
      addresses:
      - 192.168.14.2/24
      - 2000:192:168:14::2/24
      parameters:
        stp: false
