# This file provides the bridge configurations used in this repository.
#
# Copy to /etc/netplan/99-bridges.yaml on the target system.
#
# sudo cp $HOME/repos/n9kv-kvm/config/bridges/99-bridges.yaml /etc/netplan/99-bridges.yaml
# sudo chmod 600 /etc/netplan/99-bridges.yaml
# sudo netplan try
# sudo netplan apply
#
# Bridge names are outlined below, along with the nexus9000v interfaces they connect.
#
# Src Interface      Dst Interface      Bridge
# BG1_INTERFACE_1    BG2_INTERFACE_1    BR_BG1_BG2
# BG1_INTERFACE_2    SP1_INTERFACE_1    BR_BG1_SP1
# BG2_INTERFACE_2    SP2_INTERFACE_1    BR_BG2_SP2
# SP1_INTERFACE_2    LE1_INTERFACE_1    BR_SP1_LE1
# SP2_INTERFACE_2    LE2_INTERFACE_1    BR_SP2_LE2
# LE1_INTERFACE_2    HO1_INTERFACE_1    BR_LE1_HO1
# LE2_INTERFACE_2    HO2_INTERFACE_1    BR_LE2_HO2
# All mgmt0                             BR_ND_DATA

network:
  version: 2
  renderer: networkd
  vlans:
    Vlan12:
      id: 12
      link: eno6
      optional: true

  bridges:
    BR_BG1_BG2:
      dhcp4: false
      dhcp6: false
      mtu: 1500
      accept-ra: false
      parameters:
        stp: false
      interfaces: []

    BR_BG1_SP1:
      dhcp4: false
      dhcp6: false
      mtu: 1500
      accept-ra: false
      parameters:
        stp: false
      interfaces: []

    BR_BG2_SP2:
      dhcp4: false
      dhcp6: false
      mtu: 1500
      accept-ra: false
      parameters:
        stp: false
      interfaces: []

    BR_SP1_LE1:
      dhcp4: false
      dhcp6: false
      mtu: 1500
      accept-ra: false
      parameters:
        stp: false
      interfaces: []

    BR_SP2_LE2:
      dhcp4: false
      dhcp6: false
      mtu: 1500
      accept-ra: false
      parameters:
        stp: false
      interfaces: []

    BR_LE1_HO1:
      dhcp4: false
      dhcp6: false
      mtu: 1500
      accept-ra: false
      parameters:
        stp: false
      interfaces: []

    BR_LE2_HO2:
      dhcp4: false
      dhcp6: false
      mtu: 1500
      accept-ra: false
      parameters:
        stp: false
      interfaces: []

    BR_ND_DATA:
      interfaces:
      - Vlan12
      addresses:
      - 192.168.12.2/24
      - 2000:192:168:12::2/24
      accept-ra: false
      parameters:
        stp: false
