# This file provides the bridge configurations used in this repository for
# SITE1/SITE2.
#
# Copy to /etc/netplan/9912-bridges.yaml on the target system.
#
# sudo cp $HOME/repos/n9kv-kvm/config/bridges/9912-bridges.yaml /etc/netplan/9912-bridges.yaml
# sudo chmod 600 /etc/netplan/9912-bridges.yaml
# sudo netplan try
# sudo netplan apply
#
# Bridge names are outlined below, along with the nexus9000v interfaces they connect.
#
# Src Interface           Dst Interface           Bridge
# S1_BG1_INTERFACE_1      S2_BG1_INTERFACE_1      BR_ISN_S1BG1_S2BG1_1   (cross-site MSD)
# S1_BG1_INTERFACE_2      S1_SP1_INTERFACE_1      BR_S1_BG1_SP1_1
# S2_BG1_INTERFACE_2      S2_SP1_INTERFACE_1      BR_S2_BG1_SP1_1
# S1_SP1_INTERFACE_2      S1_LE1_INTERFACE_1      BR_S1_SP1_LE1_1
# S2_SP1_INTERFACE_2      S2_LE1_INTERFACE_1      BR_S2_SP1_LE1_1
# S1_LE1_INTERFACE_2      S1_H1_INTERFACE_1       BR_S1_LE1_H1_1
# S2_LE1_INTERFACE_2      S2_H1_INTERFACE_1       BR_S2_LE1_H1_1
# S1_SP1_INTERFACE_3      S1_LE2_INTERFACE_1      BR_S1_SP1_LE2_1
# S1_LE1_INTERFACE_3      S1_LE2_INTERFACE_2      BR_S1_LE1_LE2_1   (VPC peer-link)
# S1_LE1_INTERFACE_4      S1_TOR1_INTERFACE_1     BR_S1_LE1_TOR1_1
# S1_LE2_INTERFACE_3      S1_TOR1_INTERFACE_2     BR_S1_LE2_TOR1_1
# All mgmt0                                       BR_ND_DATA_12

network:
  version: 2
  renderer: networkd
  vlans:
    Vlan12:
      id: 12
      link: eno6
      optional: true

  bridges:
    BR_ISN_S1BG1_S2BG1_1:
      dhcp4: false
      dhcp6: false
      mtu: 1500
      accept-ra: false
      parameters:
        stp: false
      interfaces: []

    BR_S1_BG1_SP1_1:
      dhcp4: false
      dhcp6: false
      mtu: 1500
      accept-ra: false
      parameters:
        stp: false
      interfaces: []

    BR_S2_BG1_SP1_1:
      dhcp4: false
      dhcp6: false
      mtu: 1500
      accept-ra: false
      parameters:
        stp: false
      interfaces: []

    BR_S1_SP1_LE1_1:
      dhcp4: false
      dhcp6: false
      mtu: 1500
      accept-ra: false
      parameters:
        stp: false
      interfaces: []

    BR_S2_SP1_LE1_1:
      dhcp4: false
      dhcp6: false
      mtu: 1500
      accept-ra: false
      parameters:
        stp: false
      interfaces: []

    BR_S1_LE1_H1_1:
      dhcp4: false
      dhcp6: false
      mtu: 1500
      accept-ra: false
      parameters:
        stp: false
      interfaces: []

    BR_S2_LE1_H1_1:
      dhcp4: false
      dhcp6: false
      mtu: 1500
      accept-ra: false
      parameters:
        stp: false
      interfaces: []

    BR_S1_SP1_LE2_1:
      dhcp4: false
      dhcp6: false
      mtu: 1500
      accept-ra: false
      parameters:
        stp: false
      interfaces: []

    BR_S1_LE1_LE2_1:
      dhcp4: false
      dhcp6: false
      mtu: 1500
      accept-ra: false
      parameters:
        stp: false
      interfaces: []

    BR_S1_LE1_TOR1_1:
      dhcp4: false
      dhcp6: false
      mtu: 1500
      accept-ra: false
      parameters:
        stp: false
      interfaces: []

    BR_S1_LE2_TOR1_1:
      dhcp4: false
      dhcp6: false
      mtu: 1500
      accept-ra: false
      parameters:
        stp: false
      interfaces: []

    BR_ND_DATA_12:
      interfaces:
      - Vlan12
      addresses:
      - 192.168.12.2/24
      - 2000:192:168:12::2/24
      accept-ra: false
      parameters:
        stp: false
