# Copy this file to /etc/qemu/bridge.conf
# or append its contents to your existing file.
# If /etc/qemu doesn't exist, create it
# sudo mkdir /etc/qemu
# sudo cp $HOME/repos/n9kv-kvm/config/bridges/bridge.conf /etc/qemu/bridge.conf
# sudo chmod 600 /etc/qemu/bridge.conf
# Bridges for SITE1/SITE2
allow BR_ND_DATA_12
allow BR_ISN_S1_S2_1
allow BR_S1_BG1_SP1_1
allow BR_S2_BG1_SP1_1
allow BR_S1_SP1_LE1_1
allow BR_S2_SP1_LE1_1
allow BR_S1_LE1_H1_1
allow BR_S2_LE1_H1_1
# SITE1 VPC pair (S1_LE1 + S1_LE2) and TOR1 dual-home
allow BR_S1_SP1_LE2_1
allow BR_S1_LE1_LE2_1
allow BR_S1_LE1_T1_1
allow BR_S1_LE2_T1_1
# Bridges for WAN1 (C8000V WAN/ISN router)
allow BR_ISN_WAN_S1_1
allow BR_ISN_WAN_S2_1
# Bridges for SITE3/SITE4 (optional)
# allow BR_ND_DATA_14
# allow BR_ISN_S3_S4_1
# allow BR_S3_BG1_SP1_1
# allow BR_S4_BG1_SP1_1
# allow BR_S3_SP1_LE1_1
# allow BR_S4_SP1_LE1_1
# allow BR_S4_SP1_LE2_1
# allow BR_S4_SP1_LE3_1
# allow BR_S3_LE1_H1_1
# allow BR_S4_LE1_H1_1
# allow BR_S4_LE2_H2_1
# allow BR_S4_LE3_H2_1
