---
-   hosts: nd
    check_mode: false
    gather_facts: false
    vars:
        FABRIC_NAME: f1
        S2_IP: 192.168.11.122
        S2_MAC_1: 0000.0022.0001
        S2_MAC_2: 0000.0022.0002
    tasks:
    - name: Create f1.S2 switch policies
      cisco.dcnm.dcnm_policy:
        state: merged
        fabric: "{{ FABRIC_NAME }}"
        use_desc_as_key: true
        config:
          - switch:
            - ip: "{{ S2_IP }}"
              policies:
                - name: switch_freeform
                  create_additional_policy: false
                  priority: 101
                  description: S2_interface_mac_addresses
                  policy_vars:
                    CONF: |
                      configure terminal
                        interface Ethernet1/1
                          mac-address {{ S2_MAC_1 }}
                        interface Ethernet1/2
                          mac-address {{ S2_MAC_2 }}
