containers:
  H1:
    name: "H1"
    management_interface:
      name: "eth0"
      ip_address: "192.168.12.141"
      netmask: "24"
      bridge: "BR_ND_DATA"
      mac_address: "00:00:41:00:00:01"
      description: "Management Interface"
    test_interface:
      name: "eth1"
      ip_address: "11.1.2.141"
      netmask: "24"
      bridge: "BR_L1_H1"
      mac_address: "00:00:41:00:00:02"
      description: "Test Interface"
    vlans: []
    gateway_ip: "192.168.12.1"
    memory_kb: 1048576
    vcpus: 2

  H2:
    name: "H2"
    management_interface:
      name: "eth0"
      ip_address: "192.168.12.142"
      netmask: "24"
      bridge: "BR_ND_DATA"
      mac_address: "00:00:42:00:00:01"
      description: "Management Interface"
    test_interface:
      name: "eth1"
      ip_address: "11.1.2.142"
      netmask: "24"
      bridge: "BR_L2_H2"
      mac_address: "00:00:42:00:00:02"
      description: "Test Interface"
    vlans: []
    gateway_ip: "192.168.12.1"
    memory_kb: 1048576
    vcpus: 2