containers:
  S1_H1:
    name: "S1_H1"
    management_interface:
      name: "eth0"
      ip_address: "192.168.12.171"
      netmask: "24"
      bridge: "BR_ND_DATA_12"
      mac_address: "00:00:71:00:00:01"
      description: "Management Interface"
    test_interface:
      name: "eth1"
      ip_address: "192.0.1.171"
      netmask: "24"
      bridge: "BR_S1_T1_H1_1"
      mac_address: "00:00:71:00:00:02"
      description: "Test Interface"
    vlans: []
    gateway_ip: "192.168.12.1"
    memory_kb: 1048576
    vcpus: 2

  S2_H1:
    name: "S2_H1"
    management_interface:
      name: "eth0"
      ip_address: "192.168.12.172"
      netmask: "24"
      bridge: "BR_ND_DATA_12"
      mac_address: "00:00:72:00:00:01"
      description: "Management Interface"
    test_interface:
      name: "eth1"
      ip_address: "192.0.1.172"
      netmask: "24"
      bridge: "BR_S2_LE1_H1_1"
      mac_address: "00:00:72:00:00:02"
      description: "Test Interface"
    vlans: []
    gateway_ip: "192.168.12.1"
    memory_kb: 1048576
    vcpus: 2
